Vagrantfile
running at dd89fbc2b49cbc816b7b052a01e761d2fbd2e6b2 with 20GB of RAM resulted in errors like in the following log, truncated to a 2025 start year iteration: 
Running iteration 4 with iteration value 2025
Running step 'neighborhood_vars'
Computing accessibility variables
Computing retail_sqft_3000
Computing sum_income_3000
Computing residential_units_500
Removed 2 rows because they contain missing values
Computing residential_units_1500
Removed 2 rows because they contain missing values
Computing office_1500
Computing retail_1500
Computing industrial_1500
Computing ave_sqft_per_unit
Computing ave_lot_size_per_unit
Computing population
Computing poor
Computing renters
Computing sfdu
Computing ave_hhsize
Computing jobs_500
Computing jobs_1500
Computing ave_income_1500
Computing …
=> update memory requirements-review exact in future

baus/subsidies.py, baus/variables.py, configs/settings.yaml, run.py
@mkreilly this appears to be working...  just edit the com_for_com_fee_amounts section in settings.yaml.  Note some of the keys have been changes to be explicit about what it subsidizing what.
this functionality charges fees to new commercial development in high vmt areas that are used to subsidize commercial development in low vmt areas.  Similar functionality already existed to subsidize residential, but this is the first time we've worked towards subsidizing office (not retail yet)
=> functionality to subsidized commercial developments

data/zoning_lookup.csv
where max height is defined but max dua and max far are not, and residential building types are not allowed - we should not be assuming that when we add residential building types, that those residential buildings can take the same density of the non-residential equivalents
=> max dua to zero when no res allowed

baus/models.py, baus/summaries.py, baus/variables.py
we sometimes overfill buildings in the current code; working to fix
=> starting proportional elcm fixes

baus/summaries.py
this crashes and @conorhenley said he has been commenting it out. @fscottfoti  can we drop this line because the problem in orca has now been fixed? and all the comments above it? or?
=> drop renaming of zone id

baus.py
This PR adds an optional command line flag to `baus.py` for setting a random seed before invoking the model logic. 
For a given simulation (i.e. the same steps with the same input), this will produce identical stochastic output each time it's run.
The command line flag is `--random-seed`. It can be used in any context and does not take an argument.
Example:
`python baus.py -c --random-seed`
This was tested using the following procedure:
1. Run simulation without a random seed, and save the `runXX_taz_summaries_2010.csv` output file
`python baus.py -c -y 2010`
2. Run with a random seed, saving the same output file
`python baus.py -c -y 2010 --random-seed`
3. Run with a random seed a second time
`python baus.py -c -y 2010 --random-seed`
4. Perform a diff on the three output files. The …
=> Command line flag to set a random seed

baus/models.py, baus/utils.py
This PR fixes some bugs that were raising errors in the latest version of NumPy, v1.16. No changes to the model logic.
These problems and their fixes are discussed in more depth in Issue #96.
- In `utils.py`, a type check is added to the `constrained_normalization()` function. This converts `col_marginals` to a NumPy array if it's provided as a Pandas Series, ensuring that it can successfully be multiplied with a NumPy matrix later on. 
This resolves an error that looks like this:
`ValueError: Length of passed values is 1454, index implies 5`
- In `models.py`, the `_proportional_jobs_model()` function is modified to cast a series of job counts to integers. These values were consistently appearing as floats (in every sim iteration and multiple environments), but had been automatically …
=> Bug fixes to support NumPy 1.16

baus/summaries.py, baus/utils.py
This PR temporarily resolves a crash I was encountering in the travel_model_output step.
The error happens because the sum of households by zone that's calculated in this step produces a very small number, even though the total households looks correct. This trips a couple of different sanity-check assertions.
My solution in this PR is just to disable the assertions. It looks like some level of discrepancy is expected, so the travel model output by zone is scaled to the correct totals. But probably the zonal distributions are not correct.
We'll need to come back and track down the source of this later.
The travel_model_output step was raising an AssertionError during the first model iteration. Random seed on, scenario 4. Here's the [full …
=> Temporary fix for travel_model_output discrepancies

baus/models.py, requirements-2019.txt
This PR adds a couple of items to @smmaurer's updates to the BAUS install process in [PR #117](https://github.com/BayAreaMetro/bayarea_urbansim/pull/117). These additions assure it works in Windows (Server 2012 R2). All packages added are cross-compatible with Python 2 and Python 3, following the original work. 
They include:
- adding an argument to `update_col_from_series`, that automatically casts data to the type being used by Pandas, which seems to differ by OS
- adding the scikit-learn dependency to the install process, which does not install automatically with Pandana on Windows
- upgrading the PyTables version to be compatible with the scikit-learn version
=> Minor install additions for windows

baus/datasources.py
Four of the rows in the parcels table of `2015_09_01_bayarea_v3.h5` are missing lat-lon coordinates; rows reproduced [here](https://gist.github.com/smmaurer/9356ab43a089665a95fac37bccdf57b7).
This only recently became a problem, for reasons explained below, but the missing coordinates now raise an error the first time accessibilities are calculated. This PR adds a line of code in `datasources.py` to filter out the null parcels when the data file is loaded.
Pandana matches parcels to travel network nodes based on lat-lon coordinates, using a function in scikit-learn. Before, scikit-learn would automatically filter out points that were missing coordinates. But new versions raise an error instead.
This had initially looked like a problem in Pandana, because it showed up with Pandana v0.4 but …
=> Filter out parcels missing a location, to resolve Pandana error

baus/datasources.py
This builds on a previous PR [#124](https://github.com/BayAreaMetro/bayarea_urbansim/pull/124). In that PR, parcels with missing lat/lon were filtered out to resolve a Pandana issue. 
This created a problem in BAUS which had buildings allocated to those parcels. This PR adds those parcels back in, and assigns them lat/lon to avoid the Pandana issue-- the parcels don't have a true location, so this assigns the intended location near Stanford, specifically for use in Pandana accessibilities. Data will otherwise need to be cleaned up.
=> add xy to synthetic parcels

baus/datasources.py, baus/models.py, baus/subsidies.py, baus/summaries.py, baus/variables.py, configs/policy.yaml, configs/settings.yaml
This is another (and cleaner) approach of creating plan-specific geographic summaries. I modified `parcels_geography.csv` to add a new `pda_pba50` field and rename the previous pda field as `pda_pba40`. This way, we can avoid using `use_new_pda_id_in_topsheet` and a separate `pda_id.csv` input file to add an rename fields when creating summaries. 
This branch is also based on run-staging. I'll run both this branch and the previous "Add pba50 geographies summary - started from 'run-staging'" branch to compare the results.
=> Pba50 new input file geographic summaries - use new parcels_geography.csv with new pda IDs

baus/preprocessing.py
This PR fixes two bugs that were preventing the preprocessing steps from running (i.e. `python baus.py --mode preprocessing`).
1. There were a couple of places where the `settings` injectable needed to be updated to `mappings`, to reflect a change in yaml files from a few months ago.
2. Due to changes in the base data, I had to loosen a requirement in the `allocate_jobs()` helper function that's used in the `preproc_jobs` step.
The `baseyear_taz_controls.csv` file lists job counts for each TAZ, which are allocated to specific buildings using this code. If there are jobs but no buildings for a particular TAZ, `allocate_jobs()` raises an error and crashes.
This is now happening for a couple of TAZ's. I modified the code to log the problem and move on, which lets the remainder of the …
=> Bug fixes for the preprocessing steps

baus/datasources.py
This PR allows deed restricted units to be added to the development projects csv. Since deed restricted is a column in the preprocessed buildings table, it can also be a column in the dev proj list which gets tacked on to buildings. 
To confirm the changes generated no unintended errors, I did a test run which ran to 2050. To confirm the changes worked as intended, I added deed restricted units to the development projects table, then assessed the buildings data in 2050 to confirm that they included these units correctly. 
All was completed in the baus-env-2020 enviornment on lumodel Windows server.
=> allow dev proj to read dr from csv

baus/summaries.py
This PR adds a residential units column to the superdistrict and jurisdiction summaries, so we see how many total res units were built, rather than only SFDU and MFDU which don't capture them all. 
To test the changes I ran the model through the full simulation, which completed with no errors (given the tests we currently have). To test the new feature I checked that new  residential units column appeared in the SD and juris summaries, and that these geographies always had more total residential units than total households.
=> Add juris resunits

baus/datasources.py, baus/summaries.py
Replace the 4-letter abbreviation of jurisdiction names with the full name. The full name was added to "parcels_geography.csv".
=> Use full jurisdiction name

baus/datasources.py, baus/summaries.py
Replace numeric county IDs with text county name in output to avoid confusion, which could be caused by the different county numbering systems in parcel-related input and taz/maz input.
=> County numbering fix

baus/models.py, baus/preprocessing.py, baus/summaries.py
This PR adds a `source` column to the buildings table to distinguish buildings by: h5 buildings, pipieline buildings, and developer buildings. These show up in the buildings output to help determine where growth came from. Fletcher will be adding a field to the visualizer so that we can see this there as well. 
I ran the model to 2050 and checked that the buildings table had the correct tags as well as `parcel_output.csv` which is used by the visualizer.
=> add a source column to the buildings table

baus/summaries.py
There are currently overfull buildings in the simulation. Since the assertion for these is disabled, this reports the number of those out into the topsheet, so that we can be track them and make sure they stay in a reasonable range.
=> Add overfull info

.gitignore, baus.py, baus/datasources.py, baus/summaries.py, baus/ual.py, configs/hlcm_owner.yaml, configs/hlcm_owner_lowincome.yaml, configs/hlcm_renter.yaml, configs/hlcm_renter_lowincome.yaml, configs/inputs.yaml
This PR completes work that had previously been drafted to create "low income models", using HLCM configs. These essentially use existing household location choice models and add filters to them to get Q1 households specifically into deed restricted units. A few changes were needed to make this happen:
- added the model steps for low income owners and renters to the model flow
- added filters to the low income and non-low income models so that they only apply to households in those categories
- added filters so that non-low income households are not allowed in deed-restricted units, leaving these open so that the low-income households can choose them in the following model steps
- added two new "no unplaced" model steps for the two new "low income models", which create modified copies of …
=> Enable models so that Q1 can occupy deed restricted units

baus/datasources.py
@theocharides 
This PR is to make sure the datasource.py is updated to be consistent with the file in the urban_data_internal. 
https://github.com/BayAreaMetro/urban_data_internal/pull/13
The file included the following changes: 
- remove assigning HS buildings with only 1 unit (this prevents the removal of 35k units)
- residential units in ME buildings were dropped.
- assign s24 oppsites like s23
- exclude oppsites in s25, by assigning value 0
=> updated directory of dev proj to be consistent with urban_data_internal

baus/summaries.py
@theocharides 
I added deed restricted units into the parcel output. 
And I changed to code to get the residential unit counts from buildings table instead of parcel table - this is not really necessary. I compared the two residential unit counts, they are the same. 
This is tested with a successful round of runs. 
I am not sure how to add subsidized units into parcel output data still.
=> update summaries to include deed_restricted_units in parcel output

baus/summaries.py, baus/variables.py
Fixes the error of wrongly including `com_for_res` in `fees_per_unit` instead of `fees_per_sqft`.
=> assign com_for_res to fee_per_sqft instead of fee_per_unit

configs/hazards.yaml
Applied the same SLR conditions and mitigation to s24 as was done in s23. Checked configuration.log to confirm that the same policy setting were applied. 
Checked the hazards_slr_[year].log files to confirm that the affected parcel count was the same as s23.
=> add slr to s24

baus/summaries.py
the public land is a seperate source, and the identifier is the source column instead of the building_name column
=> change the identifier for the public land

baus/datasources.py, baus/models.py, baus/preprocessing.py, baus/subsidies.py, baus/summaries.py, configs/policy.yaml
Changes:
- s24 strategy setting in policy.yaml
- added an `inclusionary_units` column to the `buildings` table, along with adjustments to the [`overshoot` calculation in `residential_developer()` model](https://github.com/BayAreaMetro/bayarea_urbansim/commit/d06c37a455c76048084ab5ccab46596e3b9d007e#diff-1708297b6f4a38f9917cec4dd5a40299R676) and [`developer_reprocess()` model](https://github.com/BayAreaMetro/bayarea_urbansim/commit/1eab4251f06865a4d49f2a3dbff91cfad68b1255#diff-1708297b6f4a38f9917cec4dd5a40299).
- started to use `buildings` instead of `parcel_output` (which comes from `new_buildings`) in affordable units' geographic summaries. This is because `new_buildings` doesn't adjust for overshoot, so it inflates total residential_units count and inclusionary_units count a little bit …
=> Final Blueprint inclusionary strategy + new 'inclusionary_units' column in 'buildings'

baus/subsidies.py, baus/summaries.py, configs/policy.yaml
Changes:
- Added the strategy for s24.
- updated the policy setting for s23 because recent code change has changed the 'gg_id' field of `parcels_geography`.
Was able to run through year 2050 with no error. 
Compared with September release result, this strategy increased residential unit count by 150. The number is small, likely due to the fact that only a small portion of parcels fall into the cost reduction categories: 4.4% of all parcels fall into tier 1, 4.4% fall into tier 2, 2.0% fall into tier 3. The scale of cost reduction is also relatively limited: profitability increases by 2.5% for tier 1 projects, by 1.9% for tier 2 projects, and by 1.3% for tier 3 projects.
Considering these factors, I think the result makes sense.
=> Fb reduce dev cost strategy

baus/datasources.py
this new version of dp includes:
- [change dev proj output source field for oppsites](https://app.asana.com/0/385259290425521/1198196998798429/f)
- [recode type for malls and office parks](https://app.asana.com/0/385259290425521/1198205026969504/f)
- fixes of Concord, Berkeley Global Campus, Union City, Antioch, Berryessa Bart projection in this task [Clean Up Development Projects for Final BP](https://app.asana.com/0/385259290425521/1181875530353835/f)
- no dev in pge stations in this task [add to nodev for Final BP](https://app.asana.com/0/385259290425521/1181875530353840/f)
- change of HSR facility parcels from west of tunnel ave to east in [brisbane ](https://app.asana.com/0/1127632185485152/1191267997498775/f)
=> new dp data source

.gitignore, baus.py, baus/subsidies.py, baus/summaries.py, configs/policy.yaml
Changes:
1. revised the previous `subsidized_office_developer()` orca step which only applies to the VMT com_to_com strategy to a generic  `subsidized_office_developer()` function
2. coded Final Blueprint office subsidy strategy by creating office lump-sum accounts
3. created `subsidized_office_developer_lump_sum_accts()` orca step and `subsidized_office_developer_vmt()` orca step
4. created a [stand-alone script](https://github.com/BayAreaMetro/petrale/blob/master/scripts/office_lump_sum_summary.ipynb) to summarize office lump-sum acct output. The output has the same format as the residential lump-sum acct.
Note: 
1. The `non_residential_sqft` in the acctlog represents the total sqft of subsidized office buildings, rather than the 'subsidized_sqft'.
2. The sum of `non_residential_sqft` …
=> FB office lump sum acct v1

.gitignore, baus/datasources.py, configs/policy.yaml
Two things:
- new input file "2020_11_10_parcels_geography.csv"
- revised the inclusionary settings in `policy.yaml` to be consistent with the revised fbpchcat: now the inclusionary rates are set to 20% for 22 fbpchcat, 15% for 33 fbpchcat, and 10% for 153 fbpchcat. Can verify this in the `configuration.log`.
=> Fb parcels_geography_v10nov2020

.gitignore, baus/summaries.py
Fix two errors in the TAZ-level `density` and `area_type` calculations in `travel_model_output()` in `summaries.py`:
- previously, the calculations occur before [adjusting population](https://github.com/BayAreaMetro/bayarea_urbansim/blob/eabb381eca88262a3e9968d1bf81e66b5e6e7fda/baus/summaries.py#L1437) and [employment](https://github.com/BayAreaMetro/bayarea_urbansim/blob/eabb381eca88262a3e9968d1bf81e66b5e6e7fda/baus/summaries.py#L1439) based on control totals, therefore TAZ-level densities are inconsistent with the final population and employment output.
- when a TAZ has 'na' employment, the previous calculation results in "na" employment density and eventually "0" density despite positive population density. So, fill na [here](https://github.com/BayAreaMetro/bayarea_urbansim/pull/273/fil …
=> Fix taz areatype bug

baus/subsidies.py, configs/policy.yaml
- Modified the 'receiving building filter' to include `tra_id > ''`;
- Kept the same bond amount for each county's account as in Final Blueprint
=> S26 DR production strategy - shift to transit-rich locations

baus/summaries.py
https://app.asana.com/0/0/1199928036190368/f
When parcels are joined to buildings, NaNs appear where there are no buildings. This makes any diffs or other math done with those values also return NaN, instead of returning a value. 
We'll want to fillna(), starting with residential units in the parcel_data/parcel_data_diff. This came out of [✓ Fix visualizer missing projects](https://app.asana.com/0/1182664067032345/1199704448464133)
This should also likely become a data requirement and a data check. NaNs in numeric data should be 0.
=> fill na before calculating parcel_data_diff

baus/summaries/core_summaries.py, baus/visualization/push_model_files.py
This PR is Step 2 of the "Add Visualizer to BAUS" PR series. It uses the structure implemented in https://github.com/BayAreaMetro/bayarea_urbansim/pull/325 to prepare interim model outputs model upon a BAUS model run and add them to the folder containing the model's visualizer. 
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205681856882631
=> Add Visualizer to BAUS, Step 2: Add interim output viz to BAUS runs

baus-env-2023.yml, baus.py, baus/utils.py
This small PR removes the [slacker library](https://github.com/os/slacker/) dependency, used for posting to the agency slack channel. The library is archived. We replace it with the [official Python Slack SDK](https://github.com/slackapi/python-slack-sdk) instead.
`slacker` was used in `baus.py`. A separate import of `boto3` has been removed in `baus/utils.py`
=> Remove slacker dependency

baus/datasources.py, baus/variables.py
The goal of this PR was to identify any causes of run-to-run variation in model results. While some BAUS sub-models are stochastic, when the random seed is set, model results should be identical. 
The following cause of variation were found and remedied: BAUS reads in a json file that specifies parcel to mark as `nodev`. A nearest neighbor function was being used to translate between this file and the corresponding Parcel ID in the BAUS parcels table. This function sometimes returned the full set of locations from the json file but other times dropped most of them. Because the json table inherently contains a Parcel ID column, the nearest neighbor step was removed from the model run. It was confirmed that the json Parcel IDs and the nearest neighbor Parcel IDs match one another.
To test …
=> Create consistent model runs

baus/summaries/core_summaries.py
This adds a fix for creating the `interim_zone_output` output file. Previously there was an issue with `zone_id`s being lost on the households and jobs tables. This applies the same fix used in `travel_model_summaries.py` to join a `zone_id` from the parcel's table for use in these summaries.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205900307922129
=> add fix to interim zone output

baus/datasources.py, baus/summaries/core_summaries.py, baus/summaries/geographic_summaries.py, baus/summaries/travel_model_summaries.py, run_setup_PBA50Plus_DraftBlueprint.yaml, run_setup_PBA50Plus_NoProject.yaml
We need 2025 summaries - specifically core->parcel and geographic->county - so we can linearly interpolate between 2020 and 2025 to establish Draft Blueprint "initial year" metrics. (We're going to use an interpolated No Project 2023 year as the "initial year": https://app.asana.com/0/0/1207031046044722/f )
This small PR takes advantage of `interim_summary_year` which already existed, changing it from an int to an array of two ints (2025 and 2035) and updating how it is used downstream.
=> Output summaries for 2025 in addition to 2020, 2035, 2050

baus/datasources.py
Quick update to datasources.py to overwrite the as-received `geom_id`s (which were mangled, probably in Excel, at some point) with freshly calculated `geom_id`s based on `PARCEL_ID`s.
Also, I didn't make these changes in utils.py but a couple things caught my eye there.
1. Why does geom_id_to_parcel_id return a DF but parcel_id_to_geom_id returns a Series? One or the other of the function names is misleading.
2. Another way to write parcel_id_to_geom_id would be like the following:
```
def parcel_id_to_geom_id(s, parcels):
parcel_to_geom_dict = dict(zip(parcels.index, parcels.geom_id))
return s.map(parcel_to_geom_dict)
```
I'm not sure this would work exactly as written (because I'm not sure whether `orca` tables have a `.index` attribute like `pandas` DataFrames do) but something like …
=> Use PARCEL_ID to fix mangled geom_ids on initial read

baus/summaries/core_summaries.py, baus/variables.py, scripts/meta/create_run_log_from_yamls.py
Adjustments to function flow in capacity calculations for DUA and FAR. See https://app.asana.com/0/385259290425521/1208078969141846/f
=> Zoned_capacity_fix

scripts/metrics/metrics_diverse.py
UBI distorts the displacement/gentrification metrics so it has been "backed out" of these metrics as a post process.  The adjustment is applied to both DBP and FBP metrics to enable easier comparison.  See [footnote 13 in PBA 50 modeling report](https://planbayarea.org/sites/default/files/documents/Plan_Bay_Area_2050_Forecasting_Modeling_Report_October_2021.pdf) for more details on the methodology.
=> Add post-process UBI adjustment
