BayAreaMetro/bayarea_urbansim

scripts/output_csv_utils.py

trying this again here. @mkreilly @fscottfoti ok to merge these changes?

Patch compare output

---

baus/datasources.py
baus/summaries.py
run.py

create parcel level summaries with the most important parcel level data for the forecast

Parcel summaries

---

scripts/output_csv_utils.py

this variable was deprecated by the major refactor here https://github.com/MetropolitanTransportationCommission/bayarea_urbansim/commit/1e42ddf1dbcf7e63f0fd42b52d26b66ef0d0710b

remove unused variable

---

baus/subsidies.py
baus/summaries.py
baus/variables.py
configs/settings.yaml
run.py

This adds our representation of a capital gains tax, a parcel tax, small increase in profitability due to parking reduction, and adds to the total additional deed restricted units to the topsheet

Additional policies

---

baus/utils.py

@fscottfoti this is just a marker for this. not really critical at the moment.

import necessary libraries for function

---

scripts/output_csv_utils.py

when switching from the old naming scenario naming scheme to the new one i missed a few of the old scenario names in the column names.
@fscottfoti can you merge this to master please?

fix column headers

---

baus/summaries.py

@mkreilly this was tested once on the land use server and the results correspond with the description here: https://www.pivotaltracker.com/projects/1391722/stories/116924115
we can merge or leave it for @fscottfoti to do so.

Improve urban footprint summary

---

scripts/output_csv_utils.py

this way the user doesn't have to download all the necessary csv files

compare output pulls csv from ec2

---

data/development_projects.csv

as specified here https://www.pivotaltracker.com/projects/1391722/stories/117871851

add development project

---

baus/datasources.py
data/manual_edits.csv

this is mainly to get rid of that huge buildings (error) in orinda, but is a way to make individual edits to tables in the future

individual edits of cells in the buildings table, stored in a csv

---

baus/models.py
baus/summaries.py
baus/variables.py
configs/settings.yaml

this much of it just introduces the ability to make a parcel "static" which makes it nodev and also makes sure jobs do not relocate
this does not yet have the ability to do proportional growth on those same parcels
this pr also writes the account debug into out for the first time although there are a few issues with it

Static parcels

---

all.py
all2.py
baus/models.py
baus/subsidies.py
baus/summaries.py
configs/settings.yaml
requirements.txt
run.py

this should bring us up to date with the clean way of doing this.  urbansim now takes a function which takes the feasibility info and returns a probability to the profit to probability function is now actually defined in bay area urbansim
this also cleans up all and adds an all2 which experiments with different profit to probability functions

Test probability functions in dev

---

configs/settings.yaml

@mkreilly change enable_in_scenarios to the scenarios you want this in

adding representation of proposed housing bonds

---

baus/datasources.py
baus/models.py
baus/preprocessing.py
baus/summaries.py
baus/variables.py
configs/neighborhood_vars.yaml
configs/nrh.yaml
configs/settings.yaml
run.py

This removes building ids (contiguous numbers) and replace them with string identifiers.  This PR also includes a fair amount of cleanup.

Drop bldg ids

---

baus/summaries.py

county level summaries with the same fiels as TAZ summaries

county level summaries

---

baus/slr.py
configs/settings.yaml

make SLR scenario-based , add AV parking by scenario

Horizon scenarios

---

baus/models.py
configs/settings.yaml

This PR fixes a platform-specific bug that we discussed previously over here: https://github.com/BayAreaMetro/bayarea_urbansim/pull/94#issuecomment-502905983

Fixes platform-specific bug caused by int32 cast

---

baus/datasources.py

from commit https://github.com/BayAreaMetro/urban_data_internal/commit/0f63db5eb38a22882fe1c23a24463e275ad28cde

uppdate dev proj

---

configs/policy.yaml

@theocharides  please add this adjustment asap

lower sf job addition rate

---

.gitignore
baus/datasources.py

See https://github.com/BayAreaMetro/petrale/tree/master/policies/plu/base_zoning

Use hybrid basis zoning input (for zoning_lookup and zoning_parcels)

---

baus/datasources.py

@theocharides  here is the name ch in baus

update dp file name in datasources

---

.gitignore
baus/datasources.py

Remove unincorporated Marin BASIS input

Update hybrid base zoning input

---

baus/datasources.py

Updates `parcels_geography.csv` to be consistent with the 20201023 version of zmods `p10_pba50_FBP_attr_20201023.csv`.

use parcels_geography.csv based on v20201023 version of zmods attr

---

baus/datasources.py

Update 'parcels_geography.csv' to labeled nodev parcels as `nodev = 1`.
Two sources of 'nodev' parcels included in this PR:
- 35 parcels in Santa Clara county that fall into CCED and CPAD designated permanently-protected conservation areas
- 18 parcels that are glof clubs and medical centers

update parcels_geography.csv to add nodev parcels

---

baus/datasources.py

This version includes the following changes:
(1) PPA strategies: add IW buildings in PPAs (on random parcels). sqft is based on the amount of subsidy received per juridiction
(2) removed one MacArthur station questionable project
(3) adding 22k jobs in near Berryessa station
(4)exclude recology in brisbane
(5) small fixes on other Pg&E locations

new dp source 20201028

---

baus/datasources.py

PR for development projects changes reviewed by @bobbylu. Original changes were by Mark S., making changes to the public lands and malls/office parks.
PR for development projects file: https://github.com/BayAreaMetro/urban_data_internal/pull/17

update to latest dp file directory

---

.gitignore
baus/datasources.py

Based on new base zoning v10202020, with manual fixes of the hybrid index in a few jurisdictions. 
Also added version print statements for several key input files.
A test run shows that the HH growth share is 29% in Santa Clara county.

Fb new basezoning v20201105

---

configs/settings.yaml

@mkreilly I'm going to pull this in with SC = 1 for now, since we reached 34%, and then will pull it back as needed.

change SC cost

---

baus/datasources.py

using dev proj PR: https://github.com/BayAreaMetro/urban_data_internal/pull/25

update dev proj

---

baus/postprocessing.py

We don't have 2015 count of subsized unit, so for this column, we use 2050 share as the share change. 
In the code, 2015_#/2015_sum() is removed.

change subsized unit share change calculation

---

baus/models.py
baus/postprocessing.py
configs/settings.yaml

@theocharides:
I made two more changes to the code:
- changes to postprocessing.py: this change is needed to finish model run.
- changes to settings.yaml and models.py: as we discussed, these changes won't affect the model run, but will affect the output.

S26 Alt1 zoningmods 02252021 - additional changes

---

baus/datasources.py

https://github.com/BayAreaMetro/urban_data_internal/pull/30
turn on other opp sites for s26 (without GG+TRA filtering)

update dev proj- eir alt1 v2

---

configs/policy.yaml

This PR inherits Draft Blueprint VMT fee settings. 
Wil update the code more if we decide to charge a different fee level.

S26 Alt1 vmt fee

---

configs/policy.yaml

Add office subsidy strategy back to EIR Alt1, using Final Blueprint settings.

s26 EIR Alt1 use Final Blueprint office_lump_sum_acct

---

baus/datasources.py

https://github.com/BayAreaMetro/urban_data_internal/pull/31

update dev proj for s28

---

baus/datasources.py
baus/models.py
baus/postprocessing.py
baus/subsidies.py
baus/summaries.py
baus/variables.py
configs/policy.yaml

Fix places where the scenario-based pda_id column names cause errors for certain scenarios.

Fix pda id error

---

baus/summaries/affordable_housing_summaries.py
baus/summaries/core_summaries.py
baus/summaries/geographic_summaries.py
baus/summaries/hazards_summaries.py
baus/summaries/metrics.py
baus/summaries/travel_model_summaries.py

Before writing to folders, ensure they are present in the chosen output dir.

Added code to create target folders for summaries

---

baus/visualizer/BAUS_Visualizer_PBA50Plus.twb
docs/output.md

This PR adds the PPA upzoning strategy to the BAUS visualizer and makes a minor documentation update.

Add PPA Upzoning to Visualizer

---

run_setup_PBA50Plus_DBP_2020Validation.yaml
run_setup_PBA50Plus_DBP_InitialRun.yaml
run_setup_PBA50Plus_NP_Strategies.yaml

Add run setup files for the following PBA50+ runs:
- NP Initial Run
- DBP Initial Run
- DBP Initial Run with contingency/2020 updates
- NP Initial Run to set up strategies

Add run setup files

---

baus/summaries/core_summaries.py
baus/summaries/geographic_summaries.py

This mini-PR adds a few summary related updates:
Office specific vacancy rates to core summaries interim zone outputs, working with `building_type` to do so.
Adds the following variables:
* non_residential_sqft_office
* job_spaces_office
* non_residential_vacancy_office
Target summary: interim zone summary.
Comparing new vs deprecated building ids between start year and end year building microdata to identify newcomers and demolished buildings. The summary sums building square footage by parcel_id and parcel transition state (building type before and after).
The initial implementation rolls up demolished square footage by building type transition state to county, superdistrict and subregion levels,
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- …

Update core summaries with office vacancy

---

run_setup_PBA50Plus_DraftBlueprint.yaml
run_setup_PBA50Plus_NoProject.yaml
scripts/strategy_building/BAUS_zoning_lookup_outlier_clips.ipynb

This updates the PBA50+ run setup files to have the correct parcels geography columns
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207102150362287

PBA50+ run setup fix

---

scripts/strategy_building/build_PBA50Plus_NP_zoningmods.ipynb
scripts/strategy_building/build_PBA50Plus_NP_zoningmods_exp.ipynb

This PR creates a script for PBA50+ No Project zoning mods creation, which matches the PAB50+ Draft Blueprint zoning mods creation script.

Add zoning mods script for PBA50+ No Project

---

scripts/metrics/metrics_utils.py

[Add TOC growth tabulation](https://app.asana.com/0/1209436408768030/1209356108393509/f) to growth metrics.

metrics_toc to metrics_fixes branch
